- Got weather data from https://www.ncei.noaa.gov/access/past-weather/New%20York
- weather readings taken from JFK international airport, NY US (USW00094789)
- Dataset: "ncei_noaa_weather_JFK_international_airport.csv"

In [1]:
import pandas as pd

weather = "../data/ncei_noaa_weather_JFK_international_airport.csv" 
df_weather = pd.read_csv(weather, skiprows=1) # first row contains location data 
df_weather.head()

,Date,TAVG (Degrees Fahrenheit),TMAX (Degrees Fahrenheit),TMIN (Degrees Fahrenheit),PRCP (Inches),SNOW (Inches),SNWD (Inches)
0,1948-07-17,NaN,74.0,64.0,0.06,0.0,0.0
1,1948-07-18,NaN,81.0,70.0,0.00,0.0,0.0
2,1948-07-19,NaN,85.0,70.0,0.00,0.0,0.0
3,1948-07-20,NaN,84.0,69.0,0.00,0.0,0.0
4,1948-07-21,NaN,85.0,71.0,2.45,0.0,0.0

In [2]:
df_weather.shape

(28465, 7)

In [3]:
df_weather.info()

<class 'pandas.DataFrame'>
RangeIndex: 28465 entries, 0 to 28464
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Date                       28465 non-null  str
 1   TAVG (Degrees Fahrenheit)  2673 non-null   float64
 2   TMAX (Degrees Fahrenheit)  28447 non-null  float64
 3   TMIN (Degrees Fahrenheit)  28447 non-null  float64
 4   PRCP (Inches)              25574 non-null  float64
 5   SNOW (Inches)              25293 non-null  float64
 6   SNWD (Inches)              25289 non-null  float64
dtypes: float64(6), str(1)
memory usage: 1.5 MB

- Need to check all dates are in format yyyy/mm/dd before converting them into datetime
- Truncate dataset to only include dates from 2006-01-01 to 2026-03-31

### df_weather KEY
 - Date - yyyy-mm-dd 
 - TAVG - Average temperature (Degrees Fahrenheit)
 - TMAX - Max temperature for the day (Degrees Fahrenheit)
 - TMIN - Min temperature for the day (Degrees Fahrenheit)
 - PRCP - Total Precipitation (Inches)
 - SNOW - Total Snowfall (Inches)
 - SNWD - Total Snow Depth (Inches)

In [6]:
#Are all dates in the form of yyyy-mm-dd?

mask = df_weather["Date"].str.match(r"^\d{4}-\d{2}-\d{2}$", na=False)
invalid_dates = df_weather.loc[~mask, "Date"]
display(invalid_dates)

Series([], Name: Date, dtype: str)

In [9]:
print(f"Number of null or empty Date variables: {df_weather["Date"].isna().sum()}")

Number of null or empty Date variables: 0

In [10]:
#Let's convert date column into datetime
df_weather["Date"] = pd.to_datetime(df_weather["Date"])
df_weather.info()

<class 'pandas.DataFrame'>
RangeIndex: 28465 entries, 0 to 28464
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Date                       28465 non-null  datetime64[us]
 1   TAVG (Degrees Fahrenheit)  2673 non-null   float64
 2   TMAX (Degrees Fahrenheit)  28447 non-null  float64
 3   TMIN (Degrees Fahrenheit)  28447 non-null  float64
 4   PRCP (Inches)              25574 non-null  float64
 5   SNOW (Inches)              25293 non-null  float64
 6   SNWD (Inches)              25289 non-null  float64
dtypes: datetime64[us](1), float64(6)
memory usage: 1.5 MB

In [14]:
#Only need weather between 2006-01-01 and 2026-03-31
df_weather_2006_2026 = df_weather[ 
    (df_weather['Date'] >= '2006-01-01') &
    (df_weather['Date'] <= '2026-03-31')
    ].copy()

In [15]:
df_weather_2006_2026.head()

,Date,TAVG (Degrees Fahrenheit),TMAX (Degrees Fahrenheit),TMIN (Degrees Fahrenheit),PRCP (Inches),SNOW (Inches),SNWD (Inches)
20987,2006-01-01,NaN,42.0,30.0,0.00,0.0,0.0
20988,2006-01-02,NaN,45.0,34.0,0.50,0.0,0.0
20989,2006-01-03,NaN,42.0,34.0,0.98,0.0,0.0
20990,2006-01-04,NaN,39.0,28.0,0.00,0.0,0.0
20991,2006-01-05,NaN,51.0,35.0,0.04,0.0,0.0

In [16]:
df_weather_2006_2026.shape

(7395, 7)

In [17]:
df_weather_2006_2026.tail()

,Date,TAVG (Degrees Fahrenheit),TMAX (Degrees Fahrenheit),TMIN (Degrees Fahrenheit),PRCP (Inches),SNOW (Inches),SNWD (Inches)
28377,2026-03-27,NaN,61.0,39.0,0.0,0.0,0.0
28378,2026-03-28,NaN,45.0,32.0,0.0,0.0,0.0
28379,2026-03-29,NaN,49.0,29.0,0.0,0.0,0.0
28380,2026-03-30,NaN,65.0,42.0,0.0,0.0,0.0
28381,2026-03-31,NaN,68.0,48.0,0.0,0.0,0.0

In [18]:
#checking for missing values
df_weather_2006_2026.isna().sum()

Date                            0
TAVG (Degrees Fahrenheit)    7395
TMAX (Degrees Fahrenheit)       0
TMIN (Degrees Fahrenheit)       0
PRCP (Inches)                   0
SNOW (Inches)                   0
SNWD (Inches)                   3
dtype: int64

In [21]:
#Where are the missing rows for Snow Depth?
#If in summer, probably doesn't matter that they are missing - can assume they're 0
df_weather_2006_2026[df_weather_2006_2026['SNWD (Inches)'].isna()]

,Date,TAVG (Degrees Fahrenheit),TMAX (Degrees Fahrenheit),TMIN (Degrees Fahrenheit),PRCP (Inches),SNOW (Inches),SNWD (Inches)
28038,2025-04-22,NaN,75.0,50.0,0.00,0.0,NaN
28150,2025-08-12,NaN,85.0,68.0,0.00,0.0,NaN
28151,2025-08-13,NaN,85.0,72.0,0.57,0.0,NaN

- It's doubtful it snowed in August or even April, but let's check 7 days prior each of the three dates here to see if SNOW (Inches) has anything above 0.0
- And temperatures are well above freezing!

In [22]:
df_weather_2006_2026[df_weather_2006_2026["Date"].between('2025-04-15', '2025-04-22')]

,Date,TAVG (Degrees Fahrenheit),TMAX (Degrees Fahrenheit),TMIN (Degrees Fahrenheit),PRCP (Inches),SNOW (Inches),SNWD (Inches)
28031,2025-04-15,NaN,71.0,47.0,0.01,0.0,0.0
28032,2025-04-16,NaN,52.0,45.0,0.00,0.0,0.0
28033,2025-04-17,NaN,66.0,43.0,0.00,0.0,0.0
28034,2025-04-18,NaN,62.0,40.0,0.00,0.0,0.0
28035,2025-04-19,NaN,78.0,52.0,0.00,0.0,0.0
28036,2025-04-20,NaN,71.0,52.0,0.00,0.0,0.0
28037,2025-04-21,NaN,56.0,47.0,0.00,0.0,0.0
28038,2025-04-22,NaN,75.0,50.0,0.00,0.0,NaN

In [23]:
df_weather_2006_2026[df_weather_2006_2026["Date"].between('2025-08-05', '2025-08-12')]

,Date,TAVG (Degrees Fahrenheit),TMAX (Degrees Fahrenheit),TMIN (Degrees Fahrenheit),PRCP (Inches),SNOW (Inches),SNWD (Inches)
28143,2025-08-05,NaN,85.0,68.0,0.00,0.0,0.0
28144,2025-08-06,NaN,80.0,67.0,0.02,0.0,0.0
28145,2025-08-07,NaN,79.0,64.0,0.00,0.0,0.0
28146,2025-08-08,NaN,78.0,60.0,0.00,0.0,0.0
28147,2025-08-09,NaN,82.0,58.0,0.00,0.0,0.0
28148,2025-08-10,NaN,85.0,66.0,0.00,0.0,0.0
28149,2025-08-11,NaN,86.0,68.0,0.00,0.0,0.0
28150,2025-08-12,NaN,85.0,68.0,0.00,0.0,NaN

- Yes, Values are going to be zero for snow depth
- Replacing NaN with 0.0

In [24]:
# Replacing missing snow depth values with zero due to the temperature and the weather conditions in previous 7 days
df_weather_2006_2026["SNWD (Inches)"] = df_weather_2006_2026["SNWD (Inches)"].fillna(0.0)

In [25]:
#checking for missing values
df_weather_2006_2026.isna().sum()

Date                            0
TAVG (Degrees Fahrenheit)    7395
TMAX (Degrees Fahrenheit)       0
TMIN (Degrees Fahrenheit)       0
PRCP (Inches)                   0
SNOW (Inches)                   0
SNWD (Inches)                   0
dtype: int64

In [26]:
#Average temperature is completely missing so will remove column
df_weather_2006_2026 = df_weather_2006_2026.drop(columns=["TAVG (Degrees Fahrenheit)"])

In [27]:
df_weather_2006_2026.info()

<class 'pandas.DataFrame'>
RangeIndex: 7395 entries, 20987 to 28381
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Date                       7395 non-null   datetime64[us]
 1   TMAX (Degrees Fahrenheit)  7395 non-null   float64
 2   TMIN (Degrees Fahrenheit)  7395 non-null   float64
 3   PRCP (Inches)              7395 non-null   float64
 4   SNOW (Inches)              7395 non-null   float64
 5   SNWD (Inches)              7395 non-null   float64
dtypes: datetime64[us](1), float64(5)
memory usage: 346.8 KB

In [28]:
df_weather_2006_2026.head()

,Date,TMAX (Degrees Fahrenheit),TMIN (Degrees Fahrenheit),PRCP (Inches),SNOW (Inches),SNWD (Inches)
20987,2006-01-01,42.0,30.0,0.00,0.0,0.0
20988,2006-01-02,45.0,34.0,0.50,0.0,0.0
20989,2006-01-03,42.0,34.0,0.98,0.0,0.0
20990,2006-01-04,39.0,28.0,0.00,0.0,0.0
20991,2006-01-05,51.0,35.0,0.04,0.0,0.0